version: '3'

services:
 mysql:
  image: mysql:latest
  container_name: mysql
  environment:
   - MYSQL_DATABASE='aircrop'
   - MYSQL_USER='root'
   - MYSQL_ROOT_PASSWORD='root'
  ports:
   - 3306:3306
  
 
 springboot-docker-container:
  image: backend.jar
  container_name: aircrop-back
  ports:
   - 8090:8080
  build:
   context: ./
   dockerfile: Dockerfile
  depends_on:
   - mysql